project_id = "qbhqqqhvjvonbzfkyney"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-multi-channel-notification]
verify_jwt = false

[functions.reset-daily-content]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.send-email]
verify_jwt = false
