// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbhqqqhvjvonbzfkyney.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaHFxcWh2anZvbmJ6Zmt5bmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjgzMTAsImV4cCI6MjA3MDg0NDMxMH0.3hVWJQlrW6F4hktzU374wQVO_rdpxDyfwHK59W0BgI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});